### ISSUE TITLE
BayesB specifiation

### ISSUE THREAD

**Issue by stghn** [gdlc/BGLR-R#11]
I am trying to make a comparison between BayesA and BayesB with the same training and validation set. However, when I run BayesB with the option "probIn=0.01", I got almost a zero correlation between GEBV and phenotype for BayesB and  here is how I calculated the accuracy as a following code:
`ytst<-pheno[tst3];
Xtst<-X[tst3,];
ghat_tst<-Xtst%*%fm$ETA[[3]]$b;
geno_accu_tst3<-cor(ghat_tst,ytst)/h`

First, for specifying pi for BayesB, do I need to set "probIn" and "Count" to a specific value? and Second have I calculated the correlation of GEBV and phenotype in the proper way?   

Regards
Sajjad

**Comment by gdlc** [comment]
Try run it without specifying probIn or counts, just
ETA=list(list(X=XTRN,model='BayesB'))

BGLR has built-in rules to set priors that lead to (almost) non-influencial
prior.

**Comment by stghn** [comment]
Thank you for your reply. I tried your suggestion and got almost the same accuracy compared to BayesA. As mentioned in the documentation pi value for BayesB in controlled by the beta distribution. If I set "probIn=0.5" and "counts=30000", Does it gonna give me a pi=1% for BayesB? I asked this because I used the beta function in R with those values and it gave me a result of 0.01. Is it any output from BGLR to look what was the pi applied for BayesB analysis?

Regards
Sajjad

**Comment by gdlc** [comment]
If you want to have stringent marker selection, you will need to set
probIn= (very low value, e.g., 10/ncol(X)) and counts to a very large value
(e.g., counts=ncol(X)*100)

You can then play arround, probIn is the probability that any marker will
enter the model, so low values will give you stringent marker selection.
Values of 0.1 or larger will give you models similar to no variable
selection. However, probIn is inferred in BGLR. So, if you want to keep it
fixed you need to set counts to very high values, e.g., 1e6 or larger.

You can also look at posterior probability of inclusion for every marker at
fm$ETA[[i]]
$d with `i` set to the term that corresponds in your case, if you just have
markers use `i=1`.


Please do not forget to cite Perez and de los Campos (Genetics 2014) if you
use BGLR in published analyses.

Thanks for your interest

Gustavo

**Comment by stghn** [comment]
Dear Gustavo

Could you please let me know how to implement BayesC with unknown pi in BGLR?

Regards
Sajjad

**Comment by gdlc** [comment]
Just use method='BayesC'

by default pi is esitmated.

**Comment by stghn** [comment]
Thank you so much. However, If I want to run BayesC, I need to define "probIn" and "counts" in the ETA command.

**Comment by gdlc** [comment]
Not. You don't need. Try it... and read the examples.

**Comment by stghn** [comment]
As you told me, for BayesCpi, I only need to use the method "BayesC". This is for the case that the pi is unknown. How about if we want to assume the pi is known for BayesC? Do we need to do the same thing we implement for BayesB?

**Comment by gdlc** [comment]
Same thing

**Comment by stghn** [comment]
I ran the evaluation for a BayesC model two times on the same training and validation set and each time I got a different prediction result for pi (probIn). How could this possible?

**Comment by gdlc** [comment]
need more iterations? convergence problems? look at trace plots.

**Comment by stghn** [comment]
Dear Gustavo 

I was looked at the prediction of the fixed effects in my models. It seems that either in binary case or quantitative trait, the fixed effect predictions are like log regression output in R. For example, if I have 10 levels of fixed effect in the prediction output, I only have 9 fixed effect level and the first one is not present. Is it a way to calculate the missing first fixed effect somehow?

Regards
Sajjad

**Comment by gdlc** [comment]
fm$mu is the intercept

**Comment by stghn** [comment]
Based on what you said about the intercept, looking to the part of my output as an example below, how is it possible to predict the coefficient estimate of "factor(trt)1" when I have only two levels of this fixed effect? The reason I ask this question is because I need all of the coefficients of fixed and covariables to calculate the corrected phenotype. Looking to all the outputs corresponding to fixed effects do not have the first level of those fixed effects like my example shown below. 

                            "fixedeffect1"        "sd.fixedeffect1"
"factor(trt)2" -11.4589194322972 2.27550250603799


Regards
Sajjad
