### ISSUE TITLE
cross-validation for binary or categorical trait

### ISSUE THREAD

**Issue by stghn** [gdlc/BGLR-R#12]
Dear Dr. Gustavo 

To calculate the accuracy of the validation in the case of the binary or categorical trait, After fitting models with the binary and ordinal response which one of the outputs are supposed to use as a phenotype instead of the binary values to make a correlation with GEBV of the validation set? On the other hand, Which output of the binary model should be used to make a correlation with GEBV validation?

Regards

Sajjad

**Comment by gdlc** [comment]
I would not measure accuracy with corrleation for binary outcomes.

perhaps AUC or some other measures of misslcassification

**Comment by stghn** [comment]
Thank you for your response. However, based on the Binary output files, which one of those outputs can I use to calculate the accuracy of the binary values and probability values of binary trait? for example, in the binary output, we have "y" and "yhat". Does the correlation of "y" and "yhat" give us an accuracy?

Regards
Sajjad

**Comment by gdlc** [comment]
y is your oringal data, can use yHat, or $probs, the first one is on the
scale of the linear predictor, the last one on scale probability. AUC is
insensitvie to monotonic transofrmations. Should get the same results.

Note: Please do cite Perez and de los Campos Genetics (2014) if you use
BGLR for publicaiton.

Gustavo
