### ISSUE TITLE
How to predict New y when adding new samples?

### ISSUE THREAD

**Issue by xiekunwhy** [gdlc/BGLR-R#19]
Hi,

How to predict NEW y using exists training results(like marker effect...) when adding new samples(Marker ID and marker number are not changed)?

Best wishes.
Xie Kun

**Comment by xiekunwhy** [comment]
All things can be found here https://github.com/gdlc/BGLR-R/blob/master/inst/md/Validation.md.

**Comment by gdlc** [comment]
Take a look at this entry

https://github.com/gdlc/BGLR-R/blob/master/inst/md/Validation.md


There are plenty of examples that you can review at

https://github.com/gdlc/BGLR-R


Thanks for using BGLR, and please do not forget to cite
https://www.ncbi.nlm.nih.gov/pubmed/25009151  when publishing results
derived using BGLR.
