### ISSUE TITLE
R version requirement too high

### ISSUE THREAD

**Issue by agrueneberg** [gdlc/BGLR-R#2]
I don't see why this package needs R >= 3.1.3. The version requirement makes it difficult to install BGLR in many non-cutting edge environments (such as Debian).

**Comment by gdlc** [comment]
I have no idea!! Do you know how to change that?

**Comment by agrueneberg** [comment]
We would need to change this line: https://github.com/gdlc/BGLR-R/blob/master/DESCRIPTION#L7 The question is how low we can set it. I'll check if BGLR still runs on 2.15 later this week.

**Comment by agrueneberg** [comment]
I just ran the example at https://github.com/gdlc/BGLR-R/blob/master/inst/md/example_sets.md on R 2.15.1 without any problems. Maybe we could even remove the `Depends` line entirely and see if things stop working for others.

**Comment by agrueneberg** [comment]
Anyway, thanks @perpdgo! The version requirement was lowered to 2.15.0 in e1d68e19f249a8c6c5add6089819854261294a39.

**Comment by gdlc** [comment]
I think that should work fine.

Thanks!
