### ISSUE TITLE
  Unexpected number of fields in  ped file

### ISSUE THREAD

**Issue by xinshuaiqi** [gdlc/BGLR-R#30]
I have a genotype data converted from vcf to plink format in TASSEL 5.0. 

Then I tried to load the ped and map file to BGLR using `read_ped`, however, encountered the following error: 

```
Error in read_ped(f_geno) : 
  Unexpected number of fields in  qxs123_104_GenomeModelTestParents_germplasms_3kset
```

The ped file has 4006 columns, which is false for `(4006-6)%%2!=0`

Any explaination? Thank you.

**Comment by perpdgo** [comment]
The PED file is a white-space (space or tab) delimited file: the first six
columns are mandatory:

Family ID

Individual ID

Paternal ID

Maternal ID

Sex (1=male; 2=female; other=unknown)

Phenotype


After that you have 2 columns for each marker,


do you have those 6 columns?


The program opens the file, and then it takes the first line and counts the
number of

fields that are separated by space or tab. If the number of fields-6 is not
a multiple of 2, then

it raises that error, specifically in the C code:


if((p-6)%2!=0)

{

   error("Unexpected number of fields in  %s\n",ped_file);

}



So, you can send us the first three lines of the file to check it.


Regards.
