### ISSUE TITLE
Meaning of d in BGLR output

### ISSUE THREAD

**Issue by malachycampbell** [gdlc/BGLR-R#32]
Hi,
I was wondering what the meaning of 'd' is in the BGLR output. For instance if I run BayesC and and I only have markers as my linear predictors, what is fm$ETA[[1]]$d? By looking at the source code I assumed this was the model frequency. However, I would expect to see a correlation between the marker effect size and model frequency, but the correlation is close to 0.
Thanks,
Malachy

**Comment by gdlc** [comment]
Yes $d is the proportion of times a SNP entered in the model.  There should
be some assocaiation between absolute-value effect and d. Are you
correlating effect with d or absolute-value effect with d?

**Comment by malachycampbell** [comment]
I've correlated the absolute value of the marker effects with d and the correlation is ~0.09. Even if I select the top 100 markers with the largest effect the correlation is still quite low (< 0.4). Moreover, it seems that d does not vary much. The range is 0.22-0.30. The trait I am working with is regulated by a few loci with large effects, so I am a bit surprised by these results. I've attached the manhattan plots from single marker regression using a LMM and the results from BayesC.
[MMManhattan.pdf](https://github.com/gdlc/BGLR-R/files/3339648/MMManhattan.pdf)
![BayesC](https://user-images.githubusercontent.com/30236982/60349723-206f0d80-9990-11e9-9aca-f8d13bd2ddf6.png)

**Comment by gdlc** [comment]
A couple of questions and a couple of suggestions:

What is your sample size and # of SNPs?

Can you send me a manhattan plot of $d?

Comment: in BGLR we parameterize beta as betaj=bj*dj where bj~N(0,V) and
dj~Bernoulli(pi) . What you get in $b is the posterior mean of b, not of
beta. If you want to get the posterior means of beta you should use the
option 'saveEffects=TRUE', then retrieve the binary file with the samples
of beta (there is an example on the web that you can check,
https://github.com/gdlc/BGLR-R/blob/master/inst/md/example_saveEffects.md
), in some cases it will be a bit different than using $b

Even if a trait is controlled by a few loci, if N is small and the amrkers
sparse, or there is too much long range LD you could end up with models
that are not sparse enough. If you want to induce variable selection you
may need to change the prior on pi. By default we use a beta(2,2), if I
remember correctly. If you want to induce variable selection you can use
prior that would induce it e.g.


ETA=list(list(X=X,model='BayesC',saveEeffects=TRUE,probIn=2/100,counts=100))


here probIn is the prior mean of the beta and counts is the sum of the
shpae1 and shape 2 parameters....

**Comment by malachycampbell** [comment]
My data is collected from 365 individuals with 50,000 markers.
I reran the analysis with your recommendations (ETA=list(list(X=X,model='BayesC',saveEeffects=TRUE,probIn=2/100,counts=100))) and it seemed to improve the results quite a bit. The correlation between 'd' and the absolute values of beta (not $b) was ~0.88. Attached are the manhattan plots for abs(beta) and d. 

Thank you for taking the time to answer these questions in such great detail. 


[BayesC_beta_varSel.pdf](https://github.com/gdlc/BGLR-R/files/3340996/BayesC_beta_varSel.pdf)

[BayesC_d_varSel.pdf](https://github.com/gdlc/BGLR-R/files/3340998/BayesC_d_varSel.pdf)

**Comment by gdlc** [comment]
Glad it worked.

Please consider citing https://www.ncbi.nlm.nih.gov/pubmed/25009151

when using BGLR in publications

Gustavo
