### ISSUE TITLE
Adjust for genetic relationship matrix?

### ISSUE THREAD

**Issue by sariya** [gdlc/BGLR-R#34]
Dear Team,
I'd be interested to use BGLR on an admixed human population for binary outcome. However, my data are familial, that is related that are to be adjusted using a NxN genetic relationship matrix as a random variable. 

I was wondering if this package allows for that?

Thanks

**Comment by perpdgo** [comment]
Yes, it should be possible.

See 

https://github.com/gdlc/BGLR-R/blob/master/inst/md/categorical.md

You need to add the information in the linear predictor (ETA).

**Comment by gdlc** [comment]
Yes it does, take a look at this example


https://github.com/gdlc/BGLR-R/blob/master/inst/md/mixedModel.md

Please cite

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4196607/

when using BGLR in publications.
