### ISSUE TITLE
How to view the results of Cross-validation using a loop

### ISSUE THREAD

**Issue by Yoledou** [gdlc/BGLR-R#46]
Dear Dr. Gustavo
Thanks for your R package, it is very practical！
According to the provided wheat data set, I tried to do 5-fold cross-validation, but I only saw the results of the operation. How can I extract the prediction accuracy result of each verification?
when I code “cor(y,yHatCV)”, Is that right?
Yours
Yoledou

**Comment by perpdgo** [comment]
do you mean fold?
Just index the observations/predictions by fold, e.g., for fold 1 and assuming sets 
is a vector that holds the sets for cross validation:

fold<-1
cor(y[sets==fold],yHatCV[sets==fold])

**Comment by Yoledou** [comment]
Dear Dr. Gustavo 
The heritability I calculated using BGLR is significantly lower than the heritability reported in the literature. And no errors were reported during the BGLR operation. 
The following is my own code. Is there something wrong?  ?
(In the ETA settings, I set 'flock' and 'sex' in my dataset as fixed factors)

### GBLUP: Heritability Estimation
library(BGLR)
setwd('F:\\GS2\\demo\\275demo')
##dataset of phenotype
Y<-read.table("wool_1_2.txt",sep="\t",header=TRUE) 
Y$SEX <- as.factor(Y$SEX)  ##set sex into factor
Y$FLOCK <- as.factor(Y$FLOCK)  ##set flock into factor
y<-Y[,7]   select the trait “diameter of wool (DIA)”
##red_ped
out=read_ped("AMS286_QC_impute.ped")
p=out$p
n=out$n
out=out$x
out[out==2]=NA
out[out==3]=2
X=matrix(out,nrow=p,ncol=n, byrow=TRUE)
X=t(X)
X<-scale(X,center=TRUE,scale=TRUE)
G=tcrossprod(X)/ncol(X)
fm1=BGLR( y=y,ETA=list(list(~factor(FLOCK)+factor(SEX),data=Y,model='FIXED'),
                       list(K=G,model='RKHS')),
          nIter=12000,burnIn=2000,saveAt='eig_'
)


varE=scan( 'eig_varE.dat')
varU=scan('eig_ETA_G_varU.dat')
h2_2=varU/(varU+varE)
h2_2  
mean(h2_2)


The heritability of the diameter of wool in the literature is 0.57 ~ 0.59, but the heritability of the calculation after running the above code is 0.19, please help me check where the above code problems occur, why the difference is so great 
Thanks a lot !
