### ISSUE TITLE
Warnings since R 4.0 because class(MATRIX) = c("matrix", "array") now

### ISSUE THREAD

**Issue by mlell** [gdlc/BGLR-R#50]
The [line BGLR.R:500](https://github.com/gdlc/BGLR-R/blob/ec4fa60d9382b4c280187103819393cab423be37/R/BGLR.R#L500) yields a warning since R 4.0 because matrices are  now class "matrix" and "array".  Therefore, there is now a 2-logical in the if() condition. 

```{r}
if(class(LT$K)!="matrix")
```

Proposal: Use `inherits()` and never use `class(...) == x` inside if (this happens [multiple times](https://github.com/gdlc/BGLR-R/search?q=%22if%28class%22&unscoped_q=%22if%28class%22) in the code base)

**Comment by perpdgo** [comment]
Thanks for reporting this. The issue has solved in the development version.
