### ISSUE TITLE
Can I use FALSE for scale(), such as scale(X,center=FALSE, scale=FALSE)?

### ISSUE THREAD

**Issue by congzhouczcz** [gdlc/BGLR-R#51]
Hi ,when I use X<-scale(X,center=TRUE,scale=TRUE) , there are NaN in X  and 
Error in setLT.BayesBandC(LT = ETA[[i]], n = n, j = i, weights = weights,  : 
  LP 1 has NAs in X

when I set X<-scale(X,center=FALSE,scale=FALSE)  ,it ok ,
does this two parameters matter much ? Is this setting ok ?
thanks a lot!

**Comment by gdlc** [comment]
You cannot use SNPs iwht NAs in BGLR.

If the proportion of NAs is smaller than, say 5% for each SNP, then you can
impute with the mean, and then center, or center and impute 0
