### ISSUE TITLE
Multitrait function not found in Multitrait model

### ISSUE THREAD

**Issue by Dipendra031** [gdlc/BGLR-R#54]
When I run this line in multi-traits model: fm<-Multitrait(y=y,ETA=ETA,nIter=1000,burnIn=500), it says "could not find function "Multitrait".
Am I missing something here? Thanks

**Comment by gdlc** [comment]
You have to install the GitHub version, the one in CRAN don't have that
function yet.

Gustavo

**Comment by Dipendra031** [comment]
Thanks.
