### ISSUE TITLE
Option to save samples of marker effects

### ISSUE THREAD

**Issue by gregorgorjanc** [gdlc/BGLR-R#56]
Would you consider adding an option to save samples of marker effects? At the moment only samples of variances are saved, but in some downstream applications samples of marker effects would be needed. I am happy to provide a pull request should this be deemed worthy.

**Comment by perpdgo** [comment]
Hi Gregor, 

The software is able to save the samples for marker effects, see for example
https://github.com/gdlc/BGLR-R/blob/master/inst/md/example_saveEffects.md

Regards.

**Comment by gregorgorjanc** [comment]
Awesome! Thanks for pointing me to this @perpdgo ! Yay!
