### ISSUE TITLE
Resolved: On MacOS 12.6 (Monterey) ld: library not found for -lgfortran

### ISSUE THREAD

**Issue by sheinasim** [gdlc/BGLR-R#69]
Hi everyone,

I'm just offering up this solution (that worked for me to install BGLR-R) on my Mac (Intel processor) running OS 12.6.

I did this (which is a derivation of a Linux solution found here: https://stackoverflow.com/questions/6302209/building-r-package-and-error-ld-cannot-find-lgfortran):

1) install updated gcc using homebrew
2) found path to gfortran libraries (/usr/local/lib/gcc/12/)
3) create a file called "Makevar" under hidden .R directory 
4) write line "FLIBS=-L/usr/local/lib/gcc/12/"
5) source Makevar file (not sure if this was necessary)
6) installed BLGR-R in R using: install_git('https://github.com/gdlc/BGLR-R')

Hope this helps someone!

Best wishes,
Sheina

**Comment by gdlc** [comment]
Thank you very much. This is very helpful!

Gustavo

**Comment by perpdgo** [comment]
Closed
