### ISSUE TITLE
Issue with sparse response matrix

### ISSUE THREAD

**Issue by SimonRio** [gdlc/BGLR-R#74]
I have used MTM for a while now and I was quite happy with it. I recently tried to use the "Multitrait" equivalent in BGLR but I faced an issue.

I have a very sparse response matrix for which some individuals have been observed in a single environment (NAs otherwise). The matrix looks like:
           Env1    Env2     Env3     Env4     Env5
IND1   NA      2.52      NA        NA       0.23
IND2   1.37    NA        NA        NA       NA
IND3   NA      3.50      NA        NA       -2.20
IND4   -0.85   NA       2.10       -0.65    -0.22
IND5   0.24    0.07      NA        NA        NA
IND6   NA      NA       NA        NA       -0.86

When I try to run this code:

`ETA<-list(list(K=K,model="RKHS"))`
`BGLR_results <- BGLR::Multitrait(y=Y,ETA=ETA,resCov=list(type="DIAG"),nIter=1000,burnIn=500)`

I get the following error due to the absence of individuals for which observations are available in all columns:
`Error in cov(y, use = "complete.obs") : paires d'éléments incomplètes`

When running MTM, I did not have this issue for this kind of data. It seems to me that modifying `cov(y, use = "complete.obs") ` to `cov(y, use = "pairwise.complete.obs")` would at least enable the calculation when there is pairwise overlap between environments. But ideally, I would like to be able to infer parameters when there is no overlap at all between environments, which was possible with MTM.

Thanks for your help!

**Comment by perpdgo** [comment]
Hi Simon, 

Thanks for reporting the issue. Recently we modified the code to correct this, please reinstall the BGLR software from this GitHub web site and let us know if it works.

Regards.

**Comment by SimonRio** [comment]
Indeed, everything works fine now. Thanks a lot !
